- PC member of The 34th IEEE International Conference on Data Engineering (ICDE 2018), Paris, France, April 16 - 20 , 2018
- General Co-Chair of The 22nd International Conference on Database Systems for Advanced Applications (DASFAA 2017), Suzhou, China, March 27 - 30, 2017
- PC Co-Chair of The 18th Asia-Pacific Web Conference (APWeb 2016), Suzhou, China, September 23 - 25, 2016
- PC member of ACM International Conference on Management of Data (SIGMOD 2016), San Francisco, USA, June 26 - July 1, 2016
- PC member of The 24th ACM International Conference on Information and Knowledge Management (CIKM 2015), Melbourne, Australia, Oct 19-23, 2015
- PC member of ACM International Conference on Management of Data (SIGMOD 2015), Melbourne, Australia, May 31 - June 4, 2015
- PC member of The 20th International Conference on Database Systems for Advanced Applications (DASFAA 2015), Hanoi, Vietnam, April 20 - 23, 2015
- PC member of The 18th International Conference on Database Systems for Advanced Applications (DASFAA 2013), Wuhan, China, April 22 - 25, 2013
