- PC member of ACM SIGKDD 2018, London, United Kingdom. 19 - 23 August 2018
- PC member of the 27th International Joint Conference on Artificial Intelligence (IJCAI 2018), Stockholm, Sweden, July 13-19, 2018
- PC member of the 19th International Conference on Mobile Data Management (MDM 2018), Aalborg, Denmark, June 25 - 28, 2018
- PC member of the Web Conference 2018 (WWW 2018), Lyon, France, April 23 - 27, 2018
- PC member of the 34th IEEE International Conference on Data Engineering (ICDE 2018), Paris, France, April 16 - 20 , 2018
- PC member of the 23rd International Conference on Database Systems for Advanced Applications (DASFAA 2018), Gold Coast, Australia, May 21 - 24, 2018
- General Co-Chair of The 22nd International Conference on Database Systems for Advanced Applications (DASFAA 2017), Suzhou, China, March 27 - 30, 2017
- PC Co-Chair of The 18th Asia-Pacific Web Conference (APWeb 2016), Suzhou, China, September 23 - 25, 2016
- PC member of ACM International Conference on Management of Data (SIGMOD 2016), San Francisco, USA, June 26 - July 1, 2016
- PC member of the 24th ACM International Conference on Information and Knowledge Management (CIKM 2015), Melbourne, Australia, Oct 19-23, 2015
- PC member of ACM International Conference on Management of Data (SIGMOD 2015), Melbourne, Australia, May 31 - June 4, 2015
- PC member of the 20th International Conference on Database Systems for Advanced Applications (DASFAA 2015), Hanoi, Vietnam, April 20 - 23, 2015
- PC member of the 18th International Conference on Database Systems for Advanced Applications (DASFAA 2013), Wuhan, China, April 22 - 25, 2013
